### ISSUE TITLE
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by mathCrazyy** [yongzhuo/ChatGLM2-SFT#2]
在 liucong的ChatGLM-Finetuning 这个项目中，替换chatglm为chatglm2，经过一堆改动..然后在下面发生了错误。
model_engine, optimizer, _, _ = deepspeed.initialize(config=conf,
                                                         model=model,
                                                         model_parameters=model.parameters())
错误: 
RuntimeError: torch.cat(): expected a non-empty list of Tensors
好像跟你的最后一条有点像呀，不过没有看明白应该怎么改，求帮助呀，感谢感谢

**Comment by yongzhuo** [comment]
已更新，你重新克隆看看能不能解决你的问题呢
